# This file is safe from kubebuilder edit --plugins=helm/v1-alpha
# If you want to re-generate, add the --force flag.

# [MANAGER]: Manager Deployment Configurations
controllerManager:
  enable: true
  replicas: 1
  container:
    image:
      repository: ghcr.io/cobaltcore-dev/cortex
    args:
      - "--leader-elect"
      - "--metrics-bind-address=:2112"
      - "--health-probe-bind-address=:8081"
      - "--metrics-secure=false"
    resources:
      limits:
        cpu: 500m
        memory: 2048Mi
      requests:
        cpu: 10m
        memory: 64Mi
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 20
      httpGet:
        path: /healthz
        port: 8081
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      httpGet:
        path: /readyz
        port: 8081
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - "ALL"
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  terminationGracePeriodSeconds: 10
  serviceAccountName: controller-manager

# Use this to unambiguate multiple cortex deployments in the same cluster.
namePrefix: cortex

# [RBAC]: To enable RBAC (Permissions) configurations
rbac:
  enable: true
  # Whether the ironcore roles should be deployed as well.
  ironcore:
    enable: false
  pods:
    enable: false
  # Whether hypervisor operator/crd related roles should be deployed.
  # See: https://github.com/cobaltcore-dev/openstack-hypervisor-operator
  hypervisor:
    enable: false

# [CRDs]: To enable the CRDs
crd:
  # This option determines whether the CRDs are included
  # in the installation process.
  enable: true
  # Whether the ironcore crds should be deployed as well.
  ironcore:
    enable: false
  pods:
    enable: false

  # Enabling this option adds the "helm.sh/resource-policy": keep
  # annotation to the CRD, ensuring it remains installed even when
  # the Helm release is uninstalled.
  # NOTE: Removing the CRDs will also remove all cert-manager CR(s)
  # (Certificates, Issuers, ...) due to garbage collection.
  keep: true

# [METRICS]: Set to true to generate manifests for exporting metrics.
# To disable metrics export set false, and ensure that the
# ControllerManager argument "--metrics-bind-address=:8443" is removed.
metrics:
  enable: true

# [PROMETHEUS]: To enable a ServiceMonitor to export metrics to Prometheus set true
prometheus:
  enable: true

# [CERT-MANAGER]: To enable cert-manager injection to webhooks set true
certmanager:
  enable: false

# [NETWORK POLICIES]: To enable NetworkPolicies set true
networkPolicy:
  enable: false

global:
  conf: {}

# Use this to unambiguate multiple cortex deployments in the same cluster.
namePrefix: cortex
conf:
  # The scheduling domain this operator is responsible for.
  schedulingDomain: cortex
  # Used to differentiate different cortex deployments in the same cluster (e.g. leader election ID)
  leaderElectionID: cortex-unknown
  enabledControllers:
    # The explanation controller is available for all decision resources.
    - explanation-controller
