---
apiVersion: cortex.cloud/v1alpha1
kind: Step
metadata:
  name: machinepools-noop
spec:
  schedulingDomain: machines
  type: weigher
  impl: noop
  description: |
    This is only a passthrough step which assigns a zero-weight to all machinepool
    candidates. It is used as a placeholder step in the ironcore machines scheduler
    pipeline.
  knowledges: []
