# Copyright SAP SE
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.prometheus.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cortex-postgres.fullname" . }}
  labels:
    name: {{ include "cortex-postgres.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "cortex-postgres.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    any: true
  endpoints:
    - port: http-metrics
{{- end }}
