# Copyright SAP SE
# SPDX-License-Identifier: Apache-2.0

{{ if $.Capabilities.APIVersions.Has "autoscaling.k8s.io/v1/VerticalPodAutoscaler" -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "cortex-postgres.fullname" . }}-vpa
  labels:
    app: {{ include "cortex-postgres.fullname" . }}
    {{- include "cortex-postgres.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: {{ include "cortex-postgres.fullname" . }}
  updatePolicy:
    updateMode: "Initial"
    minReplicas: 1
    maxReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: {{ include "cortex-postgres.fullname" . }}
        mode: "Auto"
        minAllowed:
          cpu: {{ .Values.resources.requests.cpu }}
          memory: {{ .Values.resources.requests.memory }}
        maxAllowed:
          cpu: {{ .Values.resources.limits.cpu }}
          memory: {{ .Values.resources.limits.memory }}
        controlledResources: ["cpu", "memory"]
        controlledValues: "RequestsAndLimits"
      - containerName: {{ include "cortex-postgres.fullname" . }}-exporter
        mode: "Auto"
        minAllowed:
          cpu: {{ .Values.exporter.resources.requests.cpu }}
          memory: {{ .Values.exporter.resources.requests.memory }}
        maxAllowed:
          cpu: {{ .Values.exporter.resources.limits.cpu }}
          memory: {{ .Values.exporter.resources.limits.memory }}
        controlledResources: ["cpu", "memory"]
        controlledValues: "RequestsAndLimits"
{{- end }}
