# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

# Custom values to deploy the cortex-ironcore bundle in ironcore-in-a-box.
# See README.md for details.

cortex:
  # Grant cortex access to ironcore resources.
  crd:
    enable: true
  rbac:
    ironcore:
      enable: true
  # Use our locally built image.
  controllerManager:
    container:
      image:
        repository: cortex
        tag: dev
        pullPolicy: IfNotPresent

  # Disable all kube-prometheus-stack related resources as they are not
  # available in ironcore-in-a-box by default.
  alerts:
    enabled: false
  prometheus:
    enable: false
cortex-postgres:
  prometheus:
    enable: false
alerts:
  enabled: false
