{{- if .Values.certmanager.enable }}
# Self-signed Issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ .Values.namePrefix }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- if .Values.metrics.enable }}
---
# Certificate for the metrics
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    {{- if .Values.crd.keep }}
    "helm.sh/resource-policy": keep
    {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: metrics-certs
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - cortex.{{ .Release.Namespace }}.svc
    - cortex.{{ .Release.Namespace }}.svc.cluster.local
    - cortex-metrics-service.{{ .Release.Namespace }}.svc
  issuerRef:
    kind: Issuer
    name: {{ .Values.namePrefix }}-selfsigned-issuer
  secretName: metrics-server-cert
{{- end }}
{{- if .Values.webhook.enable }}
---
# Certificate for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ .Values.namePrefix }}-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ .Values.namePrefix }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ .Values.namePrefix }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Values.namePrefix }}-selfsigned-issuer
  secretName: {{ .Values.namePrefix }}-webhook-server-cert
{{- end }}
{{- end }}
