---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-cinder-datasource-state
spec:
  operator: cortex-cinder
  impl: datasource_state_kpi
  opts:
    datasourceOperator: cortex-cinder
  description: |
    This KPI tracks the state of datasource resources managed by cortex.
---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-cinder-knowledge-state
spec:
  operator: cortex-cinder
  impl: knowledge_state_kpi
  opts:
    knowledgeOperator: cortex-cinder
  description: |
    This KPI tracks the state of knowledge resources managed by cortex.
---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-cinder-decision-state
spec:
  operator: cortex-cinder
  impl: decision_state_kpi
  opts:
    decisionOperator: cortex-cinder
  description: |
    This aggregated KPI tracks the state of decision resources managed by cortex.
---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-cinder-kpi-state
spec:
  operator: cortex-cinder
  impl: kpi_state_kpi
  opts:
    kpiOperator: cortex-cinder
  description: |
    This KPI tracks the state of kpi resources managed by cortex.
