---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-cinder-datasource-state
spec:
  schedulingDomain: cinder
  impl: datasource_state_kpi
  opts:
    datasourceSchedulingDomain: cinder
  description: |
    This KPI tracks the state of datasource resources managed by cortex.
---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-cinder-knowledge-state
spec:
  schedulingDomain: cinder
  impl: knowledge_state_kpi
  opts:
    knowledgeSchedulingDomain: cinder
  description: |
    This KPI tracks the state of knowledge resources managed by cortex.
---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-cinder-decision-state
spec:
  schedulingDomain: cinder
  impl: decision_state_kpi
  opts:
    decisionSchedulingDomain: cinder
  description: |
    This aggregated KPI tracks the state of decision resources managed by cortex.
---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-cinder-kpi-state
spec:
  schedulingDomain: cinder
  impl: kpi_state_kpi
  opts:
    kpiSchedulingDomain: cinder
  description: |
    This KPI tracks the state of kpi resources managed by cortex.
---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-cinder-pipeline-state
spec:
  schedulingDomain: cinder
  impl: pipeline_state_kpi
  opts:
    pipelineSchedulingDomain: cinder
  description: |
    This KPI tracks the state of pipeline resources managed by cortex.
