---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cortex-cinder-metrics-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: cortex-cinder
    control-plane: controller-manager
    {{- if .Values.serviceMonitor.extraLabels }}
    {{- toYaml .Values.serviceMonitor.extraLabels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: cortex-cinder
      control-plane: controller-manager
  namespaceSelector:
    any: true