---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: netapp-storage-pool-cpu-usage-manila
spec:
  schedulingDomain: manila
  impl: netapp_storage_pool_cpu_usage_kpi
  dependencies:
    knowledges:
      - name: netapp-storage-pool-cpu-usage-manila
  description: |
    This KPI tracks the CPU usage of Manila NetApp storage pools.
---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-manila-datasource-state
spec:
  schedulingDomain: manila
  impl: datasource_state_kpi
  opts:
    datasourceSchedulingDomain: cortex-manila
  description: |
    This KPI tracks the state of datasource resources managed by cortex.
---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-manila-knowledge-state
spec:
  schedulingDomain: manila
  impl: knowledge_state_kpi
  opts:
    knowledgeSchedulingDomain: cortex-manila
  description: |
    This KPI tracks the state of knowledge resources managed by cortex.
---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-manila-decision-state
spec:
  schedulingDomain: manila
  impl: decision_state_kpi
  opts:
    decisionSchedulingDomain: cortex-manila
  description: |
    This aggregated KPI tracks the state of decision resources managed by cortex.
---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-manila-kpi-state
spec:
  schedulingDomain: manila
  impl: kpi_state_kpi
  opts:
    kpiSchedulingDomain: cortex-manila
  description: |
    This KPI tracks the state of kpi resources managed by cortex.
---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-manila-pipeline-state
spec:
  schedulingDomain: manila
  impl: pipeline_state_kpi
  opts:
    pipelineSchedulingDomain: cortex-manila
  description: |
    This KPI tracks the state of pipeline resources managed by cortex.
---
apiVersion: cortex.cloud/v1alpha1
kind: KPI
metadata:
  name: cortex-manila-step-state
spec:
  schedulingDomain: manila
  impl: step_state_kpi
  opts:
    stepSchedulingDomain: cortex-manila
  description: |
    This KPI tracks the state of step resources managed by cortex.
