# Copyright SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: cortex-cinder
description: A Helm chart deploying Cortex for Cinder.
type: application
version: 0.0.22
appVersion: 0.1.0
dependencies:
  # from: file://../../library/cortex-postgres
  - name: cortex-postgres
    repository: oci://ghcr.io/cobaltcore-dev/cortex/charts
    version: 0.5.7

  # from: file://../../../dist/chart
  - name: cortex
    repository: oci://ghcr.io/cobaltcore-dev/cortex/charts
    version: 0.0.9
    alias: cortex-knowledge-controllers
  # from: file://../../../dist/chart
  - name: cortex
    repository: oci://ghcr.io/cobaltcore-dev/cortex/charts
    version: 0.0.9
    alias: cortex-scheduling-controllers

  # Owner info adds a configmap to the kubernetes cluster with information on
  # the service owner. This makes it easier to find out who to contact in case
  # of issues. See: https://github.com/sapcc/helm-charts/pkgs/container/helm-charts%2Fowner-info
  - name: owner-info
    repository: oci://ghcr.io/sapcc/helm-charts
    version: 1.0.0
