{{- if .Values.rbac.hypervisor.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ .Values.namePrefix }}-manager-role-hypervisor
rules:
- apiGroups:
  - kvm.cloud.sap
  resources:
  - hypervisors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kvm.cloud.sap
  resources:
  - hypervisors/status
  verbs:
  - get
{{- end -}}