---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.20.0
  name: pipelines.cortex.cloud
spec:
  group: cortex.cloud
  names:
    kind: Pipeline
    listKind: PipelineList
    plural: pipelines
    singular: pipeline
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Created
      type: date
    - jsonPath: .spec.schedulingDomain
      name: Domain
      type: string
    - jsonPath: .spec.type
      name: Type
      type: string
    - jsonPath: .status.conditions[?(@.type=='AllStepsReady')].status
      name: All Steps Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Pipeline Ready
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Pipeline is the Schema for the decisions API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of Pipeline
            properties:
              createDecisions:
                default: false
                description: |-
                  If this pipeline should create decision objects.
                  When this is false, the pipeline will still process requests.
                type: boolean
              description:
                description: An optional description of the pipeline, helping understand
                  its purpose.
                type: string
              detectors:
                description: |-
                  Ordered list of detectors to apply in a descheduling pipeline.

                  This attribute is set only if the pipeline type is detector.
                  Detectors find candidates for descheduling (migration off current host).
                  These detectors are run after weighers are applied.
                items:
                  properties:
                    description:
                      description: |-
                        Additional description of the step which helps understand its purpose
                        and decisions made by it.
                      type: string
                    name:
                      description: |-
                        The name of the scheduler step in the cortex implementation.
                        Must match to a step implemented by the pipeline controller.
                      type: string
                    params:
                      description: Additional configuration for the step that can
                        be used
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  required:
                  - name
                  type: object
                type: array
              filters:
                description: |-
                  Ordered list of filters to apply in a scheduling pipeline.

                  This attribute is set only if the pipeline type is filter-weigher.
                  Filters remove host candidates from an initial set, leaving
                  valid candidates. Filters are run before weighers are applied.
                items:
                  properties:
                    description:
                      description: |-
                        Additional description of the step which helps understand its purpose
                        and decisions made by it.
                      type: string
                    name:
                      description: |-
                        The name of the scheduler step in the cortex implementation.
                        Must match to a step implemented by the pipeline controller.
                      type: string
                    params:
                      description: Additional configuration for the step that can
                        be used
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  required:
                  - name
                  type: object
                type: array
              ignorePreselection:
                default: false
                description: |-
                  If this pipeline should ignore host preselection and gather all
                  available placement candidates before applying filters, instead of
                  relying on a pre-filtered set and weights.
                type: boolean
              schedulingDomain:
                description: |-
                  SchedulingDomain defines in which scheduling domain this pipeline
                  is used (e.g., nova, cinder, manila).
                type: string
              type:
                description: |-
                  The type of the pipeline, used to differentiate between
                  filter-weigher and detector pipelines within the same
                  scheduling domain.

                  If the type is filter-weigher, the filter and weigher attributes
                  must be set. If the type is detector, the detectors attribute
                  must be set.
                enum:
                - filter-weigher
                - detector
                type: string
              weighers:
                description: |-
                  Ordered list of weighers to apply in a scheduling pipeline.

                  This attribute is set only if the pipeline type is filter-weigher.
                  These weighers are run after filters are applied.
                items:
                  properties:
                    description:
                      description: |-
                        Additional description of the step which helps understand its purpose
                        and decisions made by it.
                      type: string
                    multiplier:
                      description: |-
                        Optional multiplier to apply to the step's output.
                        This can be used to increase or decrease the weight of a step
                        relative to other steps in the same pipeline.
                      type: number
                    name:
                      description: |-
                        The name of the scheduler step in the cortex implementation.
                        Must match to a step implemented by the pipeline controller.
                      type: string
                    params:
                      description: Additional configuration for the step that can
                        be used
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  required:
                  - name
                  type: object
                type: array
            required:
            - schedulingDomain
            - type
            type: object
          status:
            description: status defines the observed state of Pipeline
            properties:
              conditions:
                description: The current status conditions of the pipeline.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
