# Copyright SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: cortex-prometheus-operator
description: Prometheus operator setup for Cortex.
type: application
version: 0.2.1
dependencies:
  # CRDs of the prometheus operator, such as PrometheusRule, ServiceMonitor, etc.
  - name: kube-prometheus-stack
    repository: oci://ghcr.io/prometheus-community/charts
    version: 82.1.1
