# This file is safe from kubebuilder edit --plugins=helm/v1-alpha
# If you want to re-generate, add the --force flag.

{{- if .Values.controllerManager.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namePrefix }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas:  {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "chart.labels" . | nindent 8 }}
        control-plane: controller-manager
        {{- if and .Values.controllerManager.pod .Values.controllerManager.pod.labels }}
        {{- range $key, $value := .Values.controllerManager.pod.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
        {{- end }}
    spec:
      containers:
        - name: manager
          args:
            {{- range .Values.controllerManager.container.args }}
            - {{ . }}
            {{- end }}
            {{- if and .Values.webhook.enable .Values.certmanager.enable }}
            - "--webhook-cert-path=/tmp/k8s-webhook-server/serving-certs"
            {{- end }}
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 2112
              protocol: TCP
            {{- if .Values.webhook.enable }}
            - name: webhook
              containerPort: 9443
              protocol: TCP
            {{- end }}
          command:
            - /manager
          image: {{ .Values.controllerManager.container.image.repository }}:{{ .Values.controllerManager.container.image.tag | default .Chart.AppVersion }}
          {{- if .Values.controllerManager.container.image.pullPolicy }}
          imagePullPolicy: {{ .Values.controllerManager.container.image.pullPolicy }}
          {{- end }}
          {{- if .Values.controllerManager.container.env }}
          env:
            {{- range $key, $value := .Values.controllerManager.container.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.controllerManager.container.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.controllerManager.container.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.controllerManager.container.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.controllerManager.container.securityContext | nindent 12 }}
          volumeMounts:
            - name: controller-manager-config-volume
              mountPath: /etc/config
            - name: controller-manager-secrets-volume
              mountPath: /etc/secrets
              readOnly: true
            {{- if and .Values.metrics.enable .Values.certmanager.enable }}
            - name: metrics-certs
              mountPath: /tmp/k8s-metrics-server/metrics-certs
              readOnly: true
            {{- end }}
            {{- if and .Values.webhook.enable .Values.certmanager.enable }}
            - name: webhook-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
            {{- end }}
      securityContext:
        {{- toYaml .Values.controllerManager.securityContext | nindent 8 }}
      serviceAccountName: {{ .Values.namePrefix }}-{{ .Values.controllerManager.serviceAccountName }}
      terminationGracePeriodSeconds: {{ .Values.controllerManager.terminationGracePeriodSeconds }}
      volumes:
        # Custom values to configure the controller-manager.
        - name: controller-manager-config-volume
          configMap:
            name: {{ .Values.namePrefix }}-controller-manager-config
        - name: controller-manager-secrets-volume
          secret:
            secretName: {{ .Values.namePrefix }}-controller-manager-secrets
        {{- if and .Values.metrics.enable .Values.certmanager.enable }}
        - name: metrics-certs
          secret:
            secretName: metrics-server-cert
        {{- end }}
        {{- if and .Values.webhook.enable .Values.certmanager.enable }}
        - name: webhook-certs
          secret:
            secretName: {{ .Values.namePrefix }}-webhook-server-cert
        {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namePrefix }}-controller-manager-config
data:
  conf.json: |-
    {{- $mergedConf := dict }}
    {{- if .Values.global.conf }}
    {{- $mergedConf = .Values.global.conf }}
    {{- end }}
    {{- if .Values.conf }}
    {{- $mergedConf = mergeOverwrite .Values.conf $mergedConf }}
    {{- end }}
    {{ toJson $mergedConf }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.namePrefix }}-controller-manager-secrets
type: Opaque
data:
  secrets.json: |-
    {{- $mergedSecrets := dict }}
    {{- if .Values.global.secrets }}
    {{- $mergedSecrets = .Values.global.secrets }}
    {{- end }}
    {{- if .Values.secrets }}
    {{- $mergedSecrets = mergeOverwrite .Values.secrets $mergedSecrets }}
    {{- end }}
    {{ toJson $mergedSecrets | b64enc }}
{{- end }}