apiVersion: rbac.authorization.k8s.io/v1
# Cluster level access is required as the controller manager has no default namespace set.
kind: ClusterRole
metadata:
  name: cortex-nova-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cortex-nova-secret-reader-binding
subjects:
  - kind: ServiceAccount
    name: cortex-nova-scheduling-controller-manager
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: cortex-nova-knowledge-controller-manager
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: cortex-nova-kpi-controller-manager
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: cortex-nova-data-controller-manager
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: cortex-nova-reservations-controller-manager
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cortex-nova-secret-reader
  apiGroup: rbac.authorization.k8s.io
