# Copyright SAP SE
# SPDX-License-Identifier: Apache-2.0

owner-info:
  enabled: true
  helm-chart-url: "https://github.com/cobaltcore-dev/cortex/helm/bundles/cortex-crds"
  maintainers:
    - "arno.uhlig@sap.com"
    - "julius.clausnitzer@sap.com"
    - "malte.viering@sap.com"
    - "marcel.bloecher@sap.com"
    - "markus.wieland@sap.com"
    - "p.matthes@sap.com"
  support-group: "workload-management"
  service: "cortex-crds"

cortex:
  # Deploy crds and cluster-rbac (clusterroles)
  crd: {enable: true}
  # Stuff we don't need in the CRD chart.
  metrics: {enable: false}
  prometheus: {enable: false}
  rbac: {enable: false}
  controllerManager: {enable: false}
  certmanager: {enable: false}
  networkPolicy: {enable: false}
